bat/*:~/.config/bat
bin/*:~/.local/bin
ghostty/config:~/Library/Application Support/com.mitchellh.ghostty/config
git/hooks/pre-commit:.git/hooks/pre-commit
lazygit/*:~/Library/Application Support/lazygit
npm/npmrc:~/.npmrc
nvim:~/.config/nvim
television/**:~/.config/television
yazi:~/.config/yazi
zsh/zshrc:~/.zshrc