[[mgr.prepend_keymap]]
on   = "<C-g>"
run  = 'shell "ghostty-tab --cwd \"$(dirname %h)\" lazygit"'
desc = "Open lazygit in a new Ghostty tab"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on   = "M"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

