#!/bin/bash
set -e

DOTFILES="$(cd "$(dirname "$0")/.." && pwd)"
dst="$HOME/.npmrc"
src="$DOTFILES/npm/npmrc"

# Extract auth lines from existing ~/.npmrc
auth_lines=""
if [ -f "$dst" ]; then
  auth_lines=$(grep '^//' "$dst" || true)
fi

# Copy template
cp "$src" "$dst"

# Add header comment with dynamic path
header="# Do not edit this file. Edit $DOTFILES/npm/npmrc and run $DOTFILES/npm/install.sh"
if grep -q "^# Do not edit" "$dst" 2>/dev/null; then
  # Update existing header with current path
  sed -i '' "s|^# Do not edit.*|$header|" "$dst"
else
  # Prepend header with blank line after
  sed -i '' "1s|^|$header\n\n|" "$dst"
fi

# Append auth lines
if [ -n "$auth_lines" ]; then
  echo "$auth_lines" >> "$dst"
fi

# Restrict permissions (auth token should not be readable by others)
chmod 600 "$dst"

echo "Updated ~/.npmrc"
